server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://192.168.9.194:3306/exam?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: false
file: 
  upload:
    dir: c:/bak/file
