server:
  port: 8078
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
file: 
  upload:
    dir: d:/bak/file
sys:
  env: local