server:
  port: 8000
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development: development

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/exam?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    
file: 
  upload:
    dir: bak/file
db:
  bak:
    dir: bak/db
    
runtime:
  timeout: 1000
  exUrl: 
  monitor: true
  
logging:
  config: config/log4j2.xml
      
token:
    expireMinute: 1440
    refreshMinute: 60
    secret: 9xzR4+K7XpvbCpoIMocXVxS655xxb9S0Qxd5RDU4b7PeSIhYfYdjg9aOMrhjPjwN

sys:
  ver: 3.2.0
